// <auto-generated />
using System;
using DealerKendaraanMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DealerKendaraanMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220616230846_AddPesananToDb")]
    partial class AddPesananToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DealerKendaraanMVC.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBelakang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDepan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("datetime2");

                    b.Property<long>("Telepon")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alamat = "jl.karimata no.8 Sumbersari",
                            Kota = "Jember",
                            NamaBelakang = "Afnan",
                            NamaDepan = "Fairuz",
                            TanggalLahir = new DateTime(2000, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2017, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = 628234692575L
                        },
                        new
                        {
                            Id = 2,
                            Alamat = "Jl.Adi Sucipto No.9,Tukangkayu",
                            Kota = "Banyuwangi",
                            NamaBelakang = "Hardiyanti",
                            NamaDepan = "Nafisah",
                            TanggalLahir = new DateTime(2001, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2019, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = 628527893087L
                        },
                        new
                        {
                            Id = 3,
                            Alamat = "Jalan raya sumber sari no. 28A",
                            Kota = "Malang",
                            NamaBelakang = "Putro",
                            NamaDepan = "Perdana",
                            TanggalLahir = new DateTime(2001, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2019, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = 628678534087L
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Kasir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaBelakang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaDepan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalMasuk")
                        .HasColumnType("datetime2");

                    b.Property<long>("Telepon")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Kasirs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Alamat = "jl.kepiting tukangkayu",
                            Kota = "Jember",
                            NamaBelakang = "Khusnul",
                            NamaDepan = "Eni",
                            TanggalLahir = new DateTime(2002, 3, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2019, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = 6281239578435L
                        },
                        new
                        {
                            Id = 2,
                            Alamat = "jl.kertanegara barat iv",
                            Kota = "Malang",
                            NamaBelakang = "Binsar",
                            NamaDepan = "Joel",
                            TanggalLahir = new DateTime(2001, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2018, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = 6285267356790L
                        },
                        new
                        {
                            Id = 3,
                            Alamat = "rnardy land, puring",
                            Kota = "Banyuwangi",
                            NamaBelakang = "Dwi",
                            NamaDepan = "Diki",
                            TanggalLahir = new DateTime(2000, 7, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalMasuk = new DateTime(2017, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Telepon = 62821216894321L
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Merk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Merks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "Honda"
                        },
                        new
                        {
                            Id = 2,
                            Nama = "Suzuki"
                        },
                        new
                        {
                            Id = 3,
                            Nama = "Yamaha"
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Pelanggan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telepon")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("Pelanggans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminId = 3,
                            Alamat = "Jl. Danau Buyan Iv/ 15, Sanur",
                            Kota = "Denpasar",
                            Nama = "Ahmad Aziz",
                            Telepon = 628456654898L
                        },
                        new
                        {
                            Id = 2,
                            AdminId = 2,
                            Alamat = "Jl. Mendut No.85, Taman Baru",
                            Kota = "Banyuangi",
                            Nama = "Arisandi",
                            Telepon = 628029542745L
                        },
                        new
                        {
                            Id = 3,
                            AdminId = 2,
                            Alamat = "perum.jember permai 3 blok P-1",
                            Kota = "Jember",
                            Nama = "Heri",
                            Telepon = 628620970885L
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Pemasok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("Alamat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kota")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaKontak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPerusahaaan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Telepon")
                        .HasColumnType("bigint");

                    b.Property<int>("TrukId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("TrukId");

                    b.ToTable("Pemasoks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdminId = 1,
                            Alamat = "Soekarno-Hatta No.3",
                            Kota = "Bandung",
                            NamaKontak = "John Sibuea",
                            NamaPerusahaaan = "PT.Honda Bng",
                            Telepon = 628674356391L,
                            TrukId = 2
                        },
                        new
                        {
                            Id = 2,
                            AdminId = 2,
                            Alamat = "jl.pranoto, petojo sel.",
                            Kota = "Jakarta",
                            NamaKontak = "Melia",
                            NamaPerusahaaan = "PT.Legenda Motor",
                            Telepon = 628653567320L,
                            TrukId = 3
                        },
                        new
                        {
                            Id = 3,
                            AdminId = 3,
                            Alamat = "Jl. Cokroaminoto No.80",
                            Kota = "Bandung",
                            NamaKontak = "Basri",
                            NamaPerusahaaan = "PT. Astra Motor",
                            Telepon = 628379054124L,
                            TrukId = 1
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Pesanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlamatPelanggan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KasirId")
                        .HasColumnType("int");

                    b.Property<string>("KotaPelanggan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NamaPelanggan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TanggalPengiriman")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalPesan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TanggalTiba")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KasirId");

                    b.ToTable("Pesanans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlamatPelanggan = "jl.danau buyan",
                            KasirId = 1,
                            KotaPelanggan = "Denpasar",
                            NamaPelanggan = "Ahmad Aziz",
                            TanggalPengiriman = new DateTime(2019, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalPesan = new DateTime(2019, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalTiba = new DateTime(2019, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AlamatPelanggan = "jl.mendut no.15",
                            KasirId = 3,
                            KotaPelanggan = "Banyuwangi",
                            NamaPelanggan = "Arisandi",
                            TanggalPengiriman = new DateTime(2019, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalPesan = new DateTime(2019, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalTiba = new DateTime(2019, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AlamatPelanggan = "perum jember permai 3",
                            KasirId = 2,
                            KotaPelanggan = "Jember",
                            NamaPelanggan = "Heri",
                            TanggalPengiriman = new DateTime(2020, 8, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalPesan = new DateTime(2020, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TanggalTiba = new DateTime(2020, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Gambar")
                        .HasColumnType("varbinary(max)");

                    b.Property<float>("HargaSatuan")
                        .HasColumnType("real");

                    b.Property<int>("MerkId")
                        .HasColumnType("int");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PemasokId")
                        .HasColumnType("int");

                    b.Property<int>("StokBarang")
                        .HasColumnType("int");

                    b.Property<string>("Warna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MerkId");

                    b.HasIndex("PemasokId");

                    b.ToTable("Produks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HargaSatuan = 250000000f,
                            MerkId = 1,
                            Nama = "Cb 100R",
                            PemasokId = 1,
                            StokBarang = 7,
                            Warna = "Merah Hitam"
                        },
                        new
                        {
                            Id = 2,
                            HargaSatuan = 750000000f,
                            MerkId = 2,
                            Nama = "Suz GSX-150",
                            PemasokId = 2,
                            StokBarang = 5,
                            Warna = "Biru"
                        },
                        new
                        {
                            Id = 3,
                            HargaSatuan = 20000000f,
                            MerkId = 3,
                            Nama = "Vixion 150",
                            PemasokId = 3,
                            StokBarang = 5,
                            Warna = "Hitam"
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Truk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Truks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nama = "Puso HINO 235 PS"
                        },
                        new
                        {
                            Id = 2,
                            Nama = "Tronton NISSAN 215 PK"
                        },
                        new
                        {
                            Id = 3,
                            Nama = "Canter HINO 235 FG"
                        });
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Pelanggan", b =>
                {
                    b.HasOne("DealerKendaraanMVC.Models.Admin", "Admin")
                        .WithMany("ManagedPelanggans")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Pemasok", b =>
                {
                    b.HasOne("DealerKendaraanMVC.Models.Admin", "Admin")
                        .WithMany("ManagedPemasoks")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerKendaraanMVC.Models.Truk", "Truk")
                        .WithMany()
                        .HasForeignKey("TrukId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Pesanan", b =>
                {
                    b.HasOne("DealerKendaraanMVC.Models.Kasir", "Kasir")
                        .WithMany("Pesanans")
                        .HasForeignKey("KasirId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DealerKendaraanMVC.Models.Produk", b =>
                {
                    b.HasOne("DealerKendaraanMVC.Models.Merk", "Merk")
                        .WithMany()
                        .HasForeignKey("MerkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DealerKendaraanMVC.Models.Pemasok", "Pemasok")
                        .WithMany()
                        .HasForeignKey("PemasokId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
